# Generated by Django 5.2.7 on 2025-10-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('actividad', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
