# Generated by Django 5.2.7 on 2025-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
